site_name: Mohamed Amine CHALHY 
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette: 



    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  

  

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - toc.integrate

plugins:
  - search
  - mkdocs-jupyter
  - blog
  
  
  - tags:
     tags_file: tag.md   
  


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

nav:
    - Home: index.md
    - About:
      - About Me: about/about.md
      
    - Projects & Notes: 
      - Projet de l'optimisation: coding/projet de l optimisation.ipynb
      - Competition Notebook: coding/ Kaggle_compet.ipynb
    
    - Tags: tag.md

    - Blog:
        - Blog:
          - blog/index.md

    
    

extra:
  generator: false





  